"""合成层 (SPECS §5.6) — 零生成, 纯程序。

- 硬切: 各镜头 trim 到叙事模板幕时长后 concat(filter_complex, 时间轴精确)。
- 口播: 每幕 TTS, atrim/apad 对齐幕时长; BGM 可选 + sidechaincompress ducking(≈-12dB, D-006)。
- 字幕: ASS 生成(默认 Noto Sans CJK) + ffmpeg burn-in, 时间轴与 TTS 对齐。
- 数字强制: 价格/优惠等数字只出现在模板 numbers 字段 → 只进字幕/贴片, 绝不进生成画面
  (compose 的文本仅来自模板 narration/numbers, 不接触镜头卡 prompt 字段)。
- 输出 H.264 竖版 1088×1920 (横版备选 1920×1088)。
- 所有 ffmpeg 命令构建为纯函数返回 argv, 可 dry-run 单测。
"""

from __future__ import annotations

import html
import subprocess

PORTRAIT_OUT = (1088, 1920)
LANDSCAPE_OUT = (1920, 1088)
DEFAULT_FONT = "Noto Sans CJK SC"
DEFAULT_FONT_SIZE = 64
DUCK_DB_DEFAULT = -12.0


def out_size(orientation: str) -> tuple[int, int]:
    if orientation == "portrait":
        return PORTRAIT_OUT
    if orientation == "landscape":
        return LANDSCAPE_OUT
    raise ValueError(f"orientation 只支持 portrait/landscape, 收到 {orientation!r}")


# ---------------- 文本/时间轴 ----------------

def render_narration(scenes: list[dict], variables: dict, numbers: dict) -> list[str]:
    """渲染每幕口播文本。占位符只允许 variables∪numbers 中已定义的字段。"""
    allowed = {**{k: str(v) for k, v in (variables or {}).items()},
               **{k: str(v) for k, v in (numbers or {}).items()}}
    out = []
    for sc in scenes:
        try:
            out.append(str(sc["narration"]).format_map(allowed))
        except KeyError as e:
            raise KeyError(f"模板 narration 引用了未定义变量: {e} (数字只可来自 numbers 字段)") from e
    return out


def build_cues(scene_durations: list[float], texts: list[str]) -> list[tuple[float, float, str]]:
    """按幕时长累加得到字幕时间轴 [(start, end, text)]。"""
    cues = []
    t = 0.0
    for d, text in zip(scene_durations, texts):
        cues.append((round(t, 3), round(t + float(d), 3), text))
        t += float(d)
    return cues


def ass_time(sec: float) -> str:
    """ASS 时间格式 H:MM:SS.CC (厘秒, 四舍五入带进位)。"""
    total_cs = int(round(max(0.0, float(sec)) * 100))
    h = total_cs // 360000
    m = (total_cs % 360000) // 6000
    s = (total_cs % 6000) // 100
    cs = total_cs % 100
    return f"{h:d}:{m:02d}:{s:02d}.{cs:02d}"


def build_ass_lines(
    cues: list[tuple[float, float, str]],
    width: int = PORTRAIT_OUT[0],
    height: int = PORTRAIT_OUT[1],
    font: str = DEFAULT_FONT,
    font_size: int = DEFAULT_FONT_SIZE,
) -> list[str]:
    """生成 ASS 文件行(不落盘), 便于单测。"""
    lines = [
        "[Script Info]",
        "; Generated by PROJECT CRADLE compose",
        f"PlayResX: {width}",
        f"PlayResY: {height}",
        "WrapStyle: 0",
        "ScaledBorderAndShadow: yes",
        "",
        "[V4+ Styles]",
        "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour,"
        " Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow,"
        " Alignment, MarginL, MarginR, MarginV, Encoding",
        f"Style: Default,{font},{font_size},&H00FFFFFF,&H000000FF,&H00000000,&H80000000,"
        "0,0,0,0,100,100,0,0,1,2,1,2,60,60,140,1",
        "",
        "[Events]",
        "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text",
    ]
    for start, end, text in cues:
        safe = html.escape(str(text), quote=False).replace("\n", "\\N")
        lines.append(
            f"Dialogue: 0,{ass_time(start)},{ass_time(end)},Default,,0,0,0,,{safe}"
        )
    return lines


def write_ass(cues, path: str, width: int, height: int, font: str = DEFAULT_FONT, font_size: int = DEFAULT_FONT_SIZE) -> str:
    lines = build_ass_lines(cues, width, height, font, font_size)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")
    return path


def escape_ass_filter_path(path: str) -> str:
    """ffmpeg filter 参数中路径转义 (ass=filename)。"""
    p = path.replace("\\", "/")
    p = p.replace(":", "\\:").replace("'", "\\'")
    return p


# ---------------- ffmpeg 命令构建(纯函数) ----------------

def build_scale_chain(w: int, h: int) -> str:
    """归一化画幅: 等比缩放+pad 补边(硬切不变形)。"""
    return (
        f"scale={w}:{h}:force_original_aspect_ratio=decrease,"
        f"pad={w}:{h}:(ow-iw)/2:(oh-ih)/2:black,setsar=1"
    )


def build_compose_argv(
    video_paths: list[str],
    scene_durations: list[float],
    voice_path: str,
    ass_path: str,
    out_path: str,
    orientation: str = "portrait",
    fps: int = 16,
    bgm_path: str | None = None,
    duck_db: float = DUCK_DB_DEFAULT,
    crf: int = 20,
) -> list[str]:
    """终混 argv: 视频 trim→concat→scale/pad→ass 烧录; 音频 trim/pad→concat→(bgm ducking)→mix。

    video_paths 条目为文件路径, 或 "color:<ffmpeg颜色>" 哨兵(程序渲染纯色贴片段, 如 CTA 字卡)。
    """
    w, h = out_size(orientation)
    n = len(video_paths)
    if n == 0:
        raise ValueError("没有可合成的镜头")
    if len(scene_durations) != n:
        raise ValueError(f"镜头数 {n} 与幕时长数 {len(scene_durations)} 不一致")

    inputs: list[str] = []
    for p, dur in zip(video_paths, scene_durations):
        if p.startswith("color:"):
            inputs += ["-f", "lavfi", "-i",
                       f"color=c={p[6:]}:s={w}x{h}:r={fps}:d={float(dur):.3f}"]
        else:
            inputs += ["-i", p]
    inputs += ["-i", voice_path]
    voice_idx = n
    bgm_idx = None
    if bgm_path:
        bgm_idx = n + 1
        inputs += ["-i", bgm_path]

    parts = []
    for i, dur in enumerate(scene_durations):
        parts.append(
            f"[{i}:v]trim=duration={float(dur):.3f},setpts=PTS-STARTPTS,{build_scale_chain(w,h)}[v{i}]"
        )
    vcat = "".join(f"[v{i}]" for i in range(n))
    parts.append(f"{vcat}concat=n={n}:v=1:a=0[vcat]")
    parts.append(f"[vcat]ass={escape_ass_filter_path(ass_path)}[vout]")

    if bgm_path is None:
        total = sum(scene_durations)
        parts.append(
            f"[{voice_idx}:a]atrim=duration={total:.3f},asetpts=PTS-STARTPTS,apad=whole_dur={total:.3f}[aout]"
        )
    else:
        lin = 10 ** (float(duck_db) / 20.0)
        parts.append(
            f"[{bgm_idx}:a]volume={lin:.4f}[bg0];"
            f"[bg0][{voice_idx}:a]sidechaincompress=threshold=0.03:ratio=12:attack=25:release=400[bgd];"
            f"[{voice_idx}:a][bgd]amix=inputs=2:duration=first:normalize=0[aout]"
        )

    argv = ["ffmpeg", "-y", "-hide_banner", "-nostats", *inputs,
            "-filter_complex", ";".join(parts),
            "-map", "[vout]", "-map", "[aout]",
            "-c:v", "libx264", "-preset", "medium", "-crf", str(crf), "-pix_fmt", "yuv420p",
            "-r", str(fps),
            "-c:a", "aac", "-b:a", "160k",
            "-shortest", "-movflags", "+faststart",
            out_path]
    return argv


def build_probe_duration_argv(path: str) -> list[str]:
    return ["ffprobe", "-v", "quiet", "-print_format", "json", "-show_format", path]


# ---------------- 编排计划 ----------------

def plan_compose(template: dict, video_by_slot: dict[str, str], variables: dict | None = None,
                 numbers: dict | None = None) -> dict:
    """依据叙事模板与「narrative_slot 或 scene.slot → 视频路径」构建合成计划。

    - 带 background 的幕(如 CTA 字卡/优惠字卡)为程序渲染纯色贴片段, 不需要镜头视频,
      数字只经 numbers 字段进入字幕 (SPECS §5.6 硬性)。
    - 钩子段(0-3s)允许 1s 短镜头。
    - 同 narrative_slot 可复用/替换镜头卡 —— 变体能力的来源 (SPECS §5.7)。
    """
    scenes = template["scenes"]

    def resolve(sc: dict):
        return video_by_slot.get(sc["slot"]) or video_by_slot.get(sc["narrative_slot"])

    missing = [sc["slot"] for sc in scenes if not sc.get("background") and resolve(sc) is None]
    if missing:
        raise ValueError(f"缺少 narrative_slot 对应的已验收镜头: {missing}")

    durations = [float(sc["duration_sec"]) for sc in scenes]
    texts = render_narration(scenes, variables if variables is not None else template.get("variables", {}),
                             numbers if numbers is not None else template.get("numbers", {}))
    cues = build_cues(durations, texts)
    video_paths = []
    for sc in scenes:
        bg = sc.get("background")
        if bg:
            video_paths.append(f"color:{bg.get('color', 'black')}")
        else:
            video_paths.append(resolve(sc))
    return {
        "template_id": template["template_id"],
        "orientation": template["orientation"],
        "slots": [sc["narrative_slot"] for sc in scenes],
        "video_paths": video_paths,
        "scene_durations": durations,
        "narration": texts,
        "cues": cues,
        "total_duration": round(sum(durations), 3),
        "numbers_used": dict(numbers if numbers is not None else template.get("numbers", {})),
    }


def compose_group(
    plan: dict,
    out_path: str,
    ass_path: str,
    tts_fn,
    runner=subprocess.run,
    bgm_path: str | None = None,
) -> dict:
    """执行合成: 每幕 TTS → 拼音轨(简单顺序 concat, 由终端混入) → 终混。

    tts_fn(text, out_path)->dict 可注入; mp3 由 ffmpeg 直接 concat 音频在终混 argv 内完成
    (voice 已是单文件; 多幕 TTS 先用 build_voice_concat_argv 合并)。
    """
    voice_files = []
    for i, text in enumerate(plan["narration"]):
        p = f"{out_path}.voice{i}.mp3"
        tts_fn(text, p)
        voice_files.append(p)
    voice_all = f"{out_path}.voice.m4a"
    if len(voice_files) == 1:
        voice_all = voice_files[0]
    else:
        argv = build_voice_concat_argv(voice_files, voice_all, scene_durations=plan["scene_durations"])
        cp = runner(argv, capture_output=True, text=True, timeout=600)
        if cp.returncode != 0:
            raise RuntimeError(f"口播音轨合成失败: {cp.stderr[-300:]}")

    w, h = out_size(plan["orientation"])
    write_ass(plan["cues"], ass_path, w, h)

    argv = build_compose_argv(
        plan["video_paths"], plan["scene_durations"], voice_all, ass_path, out_path,
        orientation=plan["orientation"], bgm_path=bgm_path,
    )
    cp = runner(argv, capture_output=True, text=True, timeout=1800)
    if cp.returncode != 0:
        raise RuntimeError(f"终混失败: {cp.stderr[-400:]}")
    return {"path": out_path, "ass": ass_path, "total_duration": plan["total_duration"]}


def build_voice_concat_argv(audio_paths: list[str], out_path: str, scene_durations: list[float]) -> list[str]:
    """多幕 TTS → 每段 atrim/apad 到幕时长 → concat a=1 (时间轴精确)。"""
    n = len(audio_paths)
    if n != len(scene_durations):
        raise ValueError("TTS 段数与幕时长数不一致")
    inputs: list[str] = []
    for p in audio_paths:
        inputs += ["-i", p]
    parts = []
    for i, dur in enumerate(scene_durations):
        parts.append(
            f"[{i}:a]atrim=duration={float(dur):.3f},asetpts=PTS-STARTPTS,apad=whole_dur={float(dur):.3f}[a{i}]"
        )
    cat = "".join(f"[a{i}]" for i in range(n))
    parts.append(f"{cat}concat=n={n}:v=0:a=1[aout]")
    return ["ffmpeg", "-y", "-hide_banner", "-nostats", *inputs,
            "-filter_complex", ";".join(parts),
            "-map", "[aout]", "-c:a", "aac", "-b:a", "160k", out_path]
